name: Darim Health Check

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
      - 'script.sh'
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Darim Client
        run: bash script.sh https://darim.vercel.app/
      - name: Darim API Gateway
        run: bash script.sh https://www.harooo.com:9600/
