name: Darim Health Check

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Darim Client
        run: if [ $(curl -s -o /dev/null -w "%{http_code}" "https://darim.vercel.app/" -v) -ne 200 ]; then; exit 1; fi
      - name: Darim API Gateway
        run: if [ $(curl -s -o /dev/null -w "%{http_code}" "https://harooo.com:9600/" -v) -ne 200 ]; then; exit 1; fi
