name: Harooo Health Check

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'  
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Harooo Hub
        run: bash script.sh https://www.harooo.com/
      - name: Harooo
        run: bash script.sh https://www.harooo.com/harooo
